### ISSUE TITLE
Can’t create new or duplicate

### ISSUE THREAD

**Issue by chrleon** [superrune/Redux-Paint#1]
The name window or save window never opens. I can switch apps and come back to Pythonista and then the name dialog comes up, but I can not do anything

Hidden file dialog
![IMG_0293](https://github.com/superrune/Redux-Paint/assets/347919/26b5673e-0fb8-4ee3-9546-f2c5c44790b4)

File dialog comes up when switching back
![IMG_0294](https://github.com/superrune/Redux-Paint/assets/347919/52563ebd-c05d-4033-bd5c-a67ae42a7d5a)

**Comment by superrune** [comment]
Hi!

There seems to be a bug in the latest Pythonista concerning alert windows on top of custom UIs. I have filed a support request, but unfortunately the Pythonista dev is really slow at answering so it can take some time before its fixed.

I need to do some artwork soon, so this is a pressing issue for me as well. Perhaps I can replace the alert windows with something of my own. I’ll look into it!

Rune

**Comment by superrune** [comment]
This issue should be fixed now. Please test and see if it works for you.

**Comment by chrleon** [comment]
I can duplicate but making a new, asks me to Clear the Editor, and the only thing that is available to click on is Cancel. Yes is only text. 
Ipad Pro 10 inch. 
Latest iOS. 
Latest Pythonista. 
Latest Redux Paint.


![Skjermbilde 2024–01–03 kl  13 19 36](https://github.com/superrune/Redux-Paint/assets/347919/a25166fe-b6f2-4432-928c-1ae52d5f8fea)

**Comment by chrleon** [comment]
Just to be sure. I can duplicate, just not make new. So duplicate and clear, is the workaround.

**Comment by superrune** [comment]
Aaah! I must have missed this when porting from Python 2 to Python 3. It should be fixed now. Thanks for reporting this!

**Comment by chrleon** [comment]
haha ok I'll test. Did a workaround to save empty.png and just duplicate that for every new image.

**Comment by chrleon** [comment]
still the same behavior I'm afraid. But I'm good for now with the workaround :)

**Comment by superrune** [comment]
That's weird! Do the "Are you sure you want to clear the editor"-window look the same now as in the screenshot above?

**Comment by chrleon** [comment]
Yup same. Checked that the file was updated in iCloud too.

--
Christian Leon Christensen

På 3. januar 2024 på 14:27:38, superrune ***@***.*** ***@***.***)) skrev:

**Comment by superrune** [comment]
New update is up! Feel free to test when you find the time 🙂 Hope I found the issue now...

**Comment by chrleon** [comment]
![IMG_E176F967E76E-1](https://github.com/superrune/Redux-Paint/assets/347919/998d3c4f-8d33-45ca-8996-6da1b6951c0b)

**Comment by superrune** [comment]
Fantastic! 😀
